package io.github.wraithyy.javacite.core.generate;

import io.github.wraithyy.javacite.core.util.Json;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Claude Code hook scripts and the merge of their registration into {@code .claude/settings.json}. */
public final class ClaudeHooksGenerator {

    public static final String FORMAT_SCRIPT = ".javacite/hook-format.sh";
    public static final String CHECK_SCRIPT = ".javacite/hook-check.sh";

    /** The {@code timeout} handler field is in seconds; the format hook runs on every edit, so it gets a tighter cap. */
    private static final int FORMAT_TIMEOUT_SECONDS = 120;

    private static final int CHECK_TIMEOUT_SECONDS = 600;

    private ClaudeHooksGenerator() {}

    /** Script path to content; the caller sets the executable bit. */
    public static Map<String, String> scripts(BuildTool tool) {
        return scripts(tool, true);
    }

    /** With {@code spotlessEnabled} false the format hook stays registered but is a no-op. */
    public static Map<String, String> scripts(BuildTool tool, boolean spotlessEnabled) {
        Map<String, String> out = new LinkedHashMap<>();
        out.put(
                FORMAT_SCRIPT,
                spotlessEnabled
                        ? Templates.load("hook-format.sh").replace("{{FORMAT_CMD}}", tool.formatFileCommand())
                        : "#!/bin/sh\n# Generated by javacite: tools.spotless is off, so there is nothing to format.\nexit 0\n");
        out.put(CHECK_SCRIPT, Templates.load("hook-check.sh").replace("{{CHECK_CMD}}", tool.quietCheckCommand()));
        return out;
    }

    /** Adds the two hook entries unless their command is already registered; unrelated keys are preserved. */
    public static String mergeSettingsJson(String existing) {
        Object parsed = existing == null || existing.isBlank() ? new LinkedHashMap<String, Object>() : Json.parse(existing);
        Map<String, Object> root = asObject(parsed, "settings.json root");
        Map<String, Object> hooks = child(root, "hooks");
        // "Edit(...)" path rules cover Write too; the guard keeps non-Java edits from spawning a process.
        addHook(hooks, "PostToolUse", "Edit|Write", FORMAT_SCRIPT, "Edit(*.java)", FORMAT_TIMEOUT_SECONDS);
        addHook(hooks, "Stop", null, CHECK_SCRIPT, null, CHECK_TIMEOUT_SECONDS);
        return Json.print(root);
    }

    private static void addHook(Map<String, Object> hooks, String event, String matcher, String script, String ifRule, int timeoutSeconds) {
        // Anchored at the project root so the hook also works when Claude's cwd is a subdirectory.
        String command = "\"$CLAUDE_PROJECT_DIR\"/" + script;
        Object existing = hooks.get(event);
        List<Object> entries = existing == null ? new ArrayList<>() : asList(existing, "hooks." + event);
        hooks.put(event, entries);
        for (Object entry : entries) {
            if (entry instanceof Map<?, ?> m && m.get("hooks") instanceof List<?> inner) {
                for (Object h : inner) {
                    // Match on the script name, not the exact command, so a re-run after the command
                    // format changed upgrades the entry in place instead of adding a duplicate.
                    if (h instanceof Map<?, ?> hm && hm.get("command") instanceof String c && c.contains(script)) {
                        @SuppressWarnings("unchecked") // hm came out of our own Json parser as a mutable map
                        Map<String, Object> mutable = (Map<String, Object>) hm;
                        mutable.put("command", command);
                        if (ifRule != null) {
                            mutable.put("if", ifRule);
                        }
                        mutable.put("timeout", BigDecimal.valueOf(timeoutSeconds));
                        return;
                    }
                }
            }
        }
        Map<String, Object> hook = new LinkedHashMap<>();
        hook.put("type", "command");
        hook.put("command", command);
        if (ifRule != null) {
            hook.put("if", ifRule);
        }
        hook.put("timeout", BigDecimal.valueOf(timeoutSeconds));
        Map<String, Object> entry = new LinkedHashMap<>();
        if (matcher != null) {
            entry.put("matcher", matcher);
        }
        entry.put("hooks", new ArrayList<Object>(List.of(hook)));
        entries.add(entry);
    }

    private static Map<String, Object> child(Map<String, Object> parent, String key) {
        Object v = parent.get(key);
        if (v == null) {
            Map<String, Object> created = new LinkedHashMap<>();
            parent.put(key, created);
            return created;
        }
        return asObject(v, key);
    }

    @SuppressWarnings("unchecked") // Json.parse only produces Map<String, Object>
    private static Map<String, Object> asObject(Object o, String what) {
        if (o instanceof Map<?, ?>) {
            return (Map<String, Object>) o;
        }
        throw new IllegalArgumentException(what + " must be a JSON object");
    }

    @SuppressWarnings("unchecked") // Json.parse only produces List<Object>
    private static List<Object> asList(Object o, String what) {
        if (o instanceof List<?>) {
            return (List<Object>) o;
        }
        throw new IllegalArgumentException(what + " must be a JSON array");
    }

    /** Loads shell templates from the classpath. */
    static final class Templates {
        private Templates() {}

        static String load(String name) {
            try (InputStream in = Templates.class.getResourceAsStream("/javacite/templates/" + name + ".tpl")) {
                if (in == null) {
                    throw new IllegalStateException("Missing template " + name);
                }
                return new String(in.readAllBytes(), StandardCharsets.UTF_8);
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        }
    }
}
