package io.github.wraithyy.javacite.core.generate;

import io.github.wraithyy.javacite.core.config.RuleLevel;
import io.github.wraithyy.javacite.core.config.Tool;
import io.github.wraithyy.javacite.core.rules.ResolvedRule;
import io.github.wraithyy.javacite.core.rules.ResolvedRules;

/**
 * Renders the enabled PMD rules as a PMD 7 ruleset.
 *
 * <p>Error rules are forced to {@code <priority>2</priority>} and {@code warn} rules to
 * {@code <priority>3</priority>}, regardless of PMD's own defaults. Maven's {@code failurePriority=2}
 * then fails only on error rules; Gradle's Pmd task has no such gate (see the plugin README).
 */
public final class PmdRulesetGenerator {

    public String generate(ResolvedRules rules) {
        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<ruleset name=\"javacite\"\n");
        sb.append("         xmlns=\"http://pmd.sourceforge.net/ruleset/2.0.0\"\n");
        sb.append("         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n");
        sb.append("         xsi:schemaLocation=\"http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd\">\n");
        sb.append("  <description>Generated by javacite. Do not edit.</description>\n");
        for (ResolvedRule r : rules.enabledFor(Tool.PMD)) {
            String ref = XmlEscape.attr(r.rule().nativeKey());
            sb.append("  <rule ref=\"").append(ref).append("\">\n");
            sb.append("    <priority>").append(r.level() == RuleLevel.WARN ? 3 : 2).append("</priority>\n");
            if (!r.rule().properties().isEmpty()) {
                sb.append("    <properties>\n");
                r.rule().properties().forEach((k, v) -> sb.append("      <property name=\"")
                        .append(XmlEscape.attr(k))
                        .append("\" value=\"")
                        .append(XmlEscape.attr(v))
                        .append("\"/>\n"));
                sb.append("    </properties>\n");
            }
            sb.append("  </rule>\n");
        }
        sb.append("</ruleset>\n");
        return sb.toString();
    }
}
