version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /buildSrc
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /javacite-maven
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /examples/maven-spring
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
