#!/bin/sh
# Claude Code PostToolUse hook: format the edited Java file. Generated by javacite.
INPUT=$(cat)
if command -v jq >/dev/null 2>&1; then
  FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
else
  FILE=$(printf '%s' "$INPUT" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
fi
case "$FILE" in
  *.java) ;;
  *) exit 0 ;;
esac
cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0
PROJECT=$(pwd -P) || exit 0
# Relative paths resolve against the project dir; the parent is resolved physically so ".." and
# symlinked directories cannot smuggle a file from outside the project past the prefix check.
case "$FILE" in
  /*) ;;
  *) FILE="$PROJECT/$FILE" ;;
esac
DIR=$(cd "${FILE%/*}/" 2>/dev/null && pwd -P) || exit 0
FILE="${DIR%/}/${FILE##*/}"
case "$FILE" in
  "$PROJECT"/*) ;;
  *) exit 0 ;;
esac
[ -f "$FILE" ] || exit 0
# FILE is absolute, so a name starting with "-" can never be parsed as an option.
# Formatting is best-effort: a failure must not block the agent's edit.
if [ -n "${JAVACITE_FORMAT_CMD:-}" ]; then
  $JAVACITE_FORMAT_CMD "$FILE" >/dev/null 2>&1 || true
else
  {{FORMAT_CMD}} >/dev/null 2>&1 || true
fi
exit 0
