#!/bin/sh
# javacite pre-commit: format staged Java files, then run the check. Generated by javacite.
# JAVACITE_FORMAT_CMD (optional) is called once per staged file with the path as its argument;
# without it all staged files are formatted in ONE build-tool invocation.
# IFS is never changed: file names are read line by line, so multi-word commands keep working.
# File names containing a newline are not supported.
TOP=$(git rev-parse --show-toplevel) || exit 1
cd "$TOP" || exit 1
# quotePath=false keeps non-ASCII names literal; C-quoted names would break git add.
FILES=$(git -c core.quotePath=false diff --cached --name-only --diff-filter=ACMR -- '*.java')
if [ -n "$FILES" ]; then
  if [ -n "${JAVACITE_FORMAT_CMD:-}" ]; then
    printf '%s\n' "$FILES" | while IFS= read -r FILE; do
      $JAVACITE_FORMAT_CMD "$FILE" </dev/null || exit 1
    done || exit 1
  else
    # Spotless takes a regex over absolute paths; escape regex metacharacters per path, join with |.
    REGEX=$(printf '%s\n' "$FILES" | while IFS= read -r FILE; do
      printf '%s\n' "$TOP/$FILE" | sed 's/[][\.*^$+?(){}|]/\\&/g'
    done | paste -s -d '|' -)
    {{FORMAT_FILES_CMD}} || exit 1
  fi
  printf '%s\n' "$FILES" | while IFS= read -r FILE; do
    # Re-staging also stages unstaged hunks of a partially staged file.
    git add -- "$FILE" || exit 1
  done || exit 1
fi
if [ -n "${JAVACITE_CHECK_CMD:-}" ]; then
  $JAVACITE_CHECK_CMD || exit 1
else
  {{CHECK_CMD}} || exit 1
fi
exit 0
