#!/bin/sh
# javacite pre-commit: run the check. Generated by javacite.
# Formatting is not part of this hook because tools.spotless is off.
TOP=$(git rev-parse --show-toplevel) || exit 1
cd "$TOP" || exit 1
if [ -n "${JAVACITE_CHECK_CMD:-}" ]; then
  $JAVACITE_CHECK_CMD || exit 1
else
  {{CHECK_CMD}} || exit 1
fi
exit 0
