package io.github.wraithyy.javacite.core.docs;

import io.github.wraithyy.javacite.core.config.RuleLevel;
import io.github.wraithyy.javacite.core.config.Tool;
import io.github.wraithyy.javacite.core.rules.Rule;
import io.github.wraithyy.javacite.core.rules.RuleRegistry;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * Renders {@code docs/rules.md} from the bundled rule registry.
 *
 * <p>Usage: {@code RulesDocGenerator <output-file> [--check]}. With {@code --check} nothing is written and the exit
 * status is 1 when the file differs from the registry.
 */
public final class RulesDocGenerator {

    private static final String LS = "\n";

    private RulesDocGenerator() {}

    public static String generate() {
        return generate(RuleRegistry.load().rules());
    }

    static String generate(List<Rule> rules) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!-- GENERATED by RulesDocGenerator from rules-registry.yml. Do not edit; run ")
                .append("`./gradlew generateRulesDoc`. -->")
                .append(LS)
                .append("# Rule reference")
                .append(LS)
                .append(LS)
                .append("> This file is generated from `javacite-core/src/main/resources/javacite/rules-registry.yml`. ")
                .append("Do not edit it by hand.")
                .append(LS)
                .append(LS)
                .append(rules.size())
                .append(" rules. Every rule is listed at its default level; set any id under `rules:` in ")
                .append("`javacite.yml` to `error`, `warn` or `off` (see [configuration](configuration.md)). ")
                .append("The agent text is what appears in the generated `AGENTS.md` while the rule is enabled.")
                .append(LS)
                .append(LS);
        for (Tool tool : Tool.values()) {
            List<Rule> forTool =
                    rules.stream().filter(r -> r.tool() == tool).toList();
            if (!forTool.isEmpty()) {
                section(sb, tool, forTool);
            }
        }
        return sb.toString();
    }

    private static void section(StringBuilder sb, Tool tool, List<Rule> rules) {
        sb.append("## ").append(tool.key()).append(" (").append(rules.size()).append(")").append(LS).append(LS);
        sb.append("| Id | Default | Category | Sonar | Agent text |").append(LS);
        sb.append("|---|---|---|---|---|").append(LS);
        for (Rule r : rules) {
            sb.append("| `")
                    .append(r.id())
                    .append("` | ")
                    .append(level(r.defaultLevel()))
                    .append(" | ")
                    .append(cell(r.category()))
                    .append(" | ")
                    .append(r.sonarKeys().stream().map(k -> "`" + k + "`").collect(Collectors.joining(", ")))
                    .append(" | ")
                    .append(cell(r.agentText()))
                    .append(" |")
                    .append(LS);
        }
        sb.append(LS);
    }

    private static String level(RuleLevel level) {
        return level.name().toLowerCase(Locale.ROOT);
    }

    private static String cell(String text) {
        return text.strip().replace("|", "\\|").replace("\n", " ");
    }

    public static void main(String[] args) throws IOException {
        if (args.length < 1 || args.length > 2 || (args.length == 2 && !"--check".equals(args[1]))) {
            System.err.println("usage: RulesDocGenerator <output-file> [--check]");
            System.exit(2);
        }
        Path file = Path.of(args[0]);
        String expected = generate();
        if (args.length == 2) {
            String actual = Files.isRegularFile(file) ? Files.readString(file, StandardCharsets.UTF_8) : "";
            if (!expected.equals(actual)) {
                System.err.println(file + " is stale; run ./gradlew generateRulesDoc and commit the result");
                System.exit(1);
            }
            return;
        }
        Files.createDirectories(file.toAbsolutePath().getParent());
        Files.writeString(file, expected, StandardCharsets.UTF_8);
    }
}
