#!/bin/sh
# Claude Code Stop hook: run the javacite check, exit 2 with the tail of the output on failure. Generated by javacite.
INPUT=$(cat)
# Without this guard a failing check would re-trigger the hook forever.
if printf '%s' "$INPUT" | grep -Eq '"stop_hook_active"[[:space:]]*:[[:space:]]*true'; then
  exit 0
fi
cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0
if [ -n "${JAVACITE_CHECK_CMD:-}" ]; then
  OUT=$($JAVACITE_CHECK_CMD 2>&1)
else
  OUT=$(./gradlew -q javaciteCheck 2>&1)
fi
STATUS=$?
if [ "$STATUS" -ne 0 ]; then
  printf '%s\n' "$OUT" | tail -n 40 >&2
  exit 2
fi
exit 0
